Message.create(greeting: "Hello world!")
Message.create(greeting: "Greetings to the wonderful people of Microverse!")
Message.create(greeting: "Welcome to Rails React!")
Message.create(greeting: "Hi there!")
Message.create(greeting: "You are welcome to this channel!")
